code/core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include("django.contrib.auth.urls")),
    path('accounts/', include("accounts.urls")),
    path('treino/', include("Treino.urls")),
    path('prontuario/', include("Prontuario.urls")),
    path('horario/', include("Horario.urls")),
    path('consulta/', include("Consulta.urls")),
    path('dieta/', include("Dieta.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/core/apps/Dieta/models.py
from django.db import models
from accounts.models import Usuario
# Create your models here.
from Consulta.models import Consulta

class Dieta( models.Model ):
    
    diaSemana = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        choices=[
            ('SF','Segunda-feira'),
            ('TF','Terça-feira'),
            ('QAF','Quarta-feira'),
            ('QIF','Quinta-feira'),
            ('SF','Sexta-feira'),
            ('S','Sábado'),
            ('D','Domingo'),
        ]
    )

    quantidade = models.CharField(
        max_length=255,
        blank=False,
        null=False
    )

    alimento = models.CharField(
        max_length=255,
        blank=False,
        null=False
    )

    horario = models.CharField(
        max_length=255,
        blank=False,
        null=False
    )

    consulta = models.ForeignKey(
        Consulta, 
        on_delete=models.CASCADE,
        related_name='dieta',
    )

code/core/apps/Horario/models.py
from accounts.models import Usuario
from django.db import models
from datetime import time
# Create your models here.

class Horario( models.Model ):
    
    data = models.DateField(
        help_text="Insira uma data para agenda",
        blank=False,
        null=False,
    )

    
    hora = models.TimeField(
        blank=False,
        null=False,
        default=time(10, 0)
    )

    preenchido = models.BooleanField(
        blank=False,
        null=False,
        default=False,
    )

    profissional = models.ForeignKey(
        Usuario, 
        on_delete=models.CASCADE,
        related_name='professionalH',
    )

code/core/templates/Base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static '/assets/logo.png' %}" rel="icon">
  <link href="{% static '/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  <script src="https://kit.fontawesome.com/12608b871a.js" crossorigin="anonymous"></script>
  <!-- Vendor CSS Files -->
  <link href="{% static '/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  
  {%block head%} {% endblock %}

  <!-- Template Main CSS File -->
  <link href="{% static '/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin
  * Updated: May 30 2023 with Bootstrap v5.3.0
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  {% include './Header.html' %}
  
  <main id="main" class="main">
    {% include './sidebar.html' %}


    {% block pagetitle %}

    {% endblock %}
  

    {% block content %}

    {% endblock %}

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static '/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static '/assets/vendor/quill/quill.min.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static '/js/main.js' %}"></script>

</body>

</html>

code/core/templates/Header.html
  <!-- ======= Header ======= -->
  {% load bootstrap %}

  {% load static %}

  <header id="header" class="header fixed-top d-flex align-items-center pr-4">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'home'%}" class="logo d-flex align-items-center">
        <img src="{% static '/assets/logo.png' %}" alt="oi">
        <span class="d-none d-lg-block">NutriAtivo</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

   

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->



        <li class="nav-item dropdown pe-3">
          

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            {% if request.user.usuario.foto %}
                <img width="30" height="30" src="{{ request.user.usuario.foto.url }}" alt="Profile" class="rounded-circle">
                &#160;
                {% else %}
                <i class="fas fa-user"></i>
                {% endif %}
            <span class="d-none d-md-block dropdown-toggle ps-2">{{ request.user.username }}  </span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{ request.user.username }}</h6>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'profile' %}">
                
                <i class="fas fa-user"></i>
                <span>Meu perfil</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>
            {% if user.is_authenticated %}
              <li>
                <a class="dropdown-item d-flex align-items-center" href="/accounts/logout?next=/accounts/login/">
                  <i class="bi bi-box-arrow-right"></i>
                  <span>Sair</span>
                </a>
              </li>
            {% else %}
              <li>
                <a class="dropdown-item d-flex align-items-center" href="/accounts/login/">
                  <i class="bi bi-box-arrow-right"></i>
                  <span>Entrar</span>
                </a>
              </li>
            {% endif %}
          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

code/core/templates/baselogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%block head%} {% endblock %}
    <link rel="shortcut icon" href="{% static '/assets/favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static '/style/style.css' %}">
</head>
<body>

    <div class="wrapper">
        {% include './navbar.html' %}

        {%block content%}


        {% endblock %}
    
    </div>
    <script>
        document.querySelectorAll('.field input').forEach(e => {
            e.setAttribute('placeholder', ' ');
        });

        document.querySelectorAll('.field label').forEach(e => {
            if ( e.innerText.search(':') === String(e.innerText).length - 1) {
                e.innerText = String(e.innerText).slice(0, String(e.innerText).length - 1);
            }
        })
    </script>
</body>
</html>

code/core/templates/dashboard-base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    {% block head %}
    {% endblock %}
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
  <!-- Nucleo Icons -->
  <link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- CSS Files -->
  <link id="pagestyle" href="{% static 'css/soft-ui-dashboard.css' %}" rel="stylesheet" />

  <!-- Nepcha Analytics (nepcha.com) -->
  <!-- Nepcha is a easy-to-use web analytics. No cookies and fully compliant with GDPR, CCPA and PECR. -->
  <script defer data-site="YOUR_DOMAIN_HERE" src="https://api.nepcha.com/js/nepcha-analytics.js"></script>
</head>

<body class="g-sidenav-show  bg-gray-100">
  
  {% block content %}

  {% endblock %}
  
  <!--   Core JS Files   -->
  <script src="{% static 'js/core/popper.min.js' %}"></script>
  <script src="{% static 'js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
  <script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
  <script src="{% static 'js/plugins/chartjs.min.js' %}"></script>
  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'js/soft-ui-dashboard.min.js' %}"></script>
</body>

</html>

code/core/templates/detalharPlanoTrabalho.html
{% extends 'Base.html' %}

{% load static %}

{% block head %}
<title>Agenda de {{ request.user.username }} </title>
{% endblock %}

{% block pagetitle %}
<div class="pagetitle">
    <h1>Gerenciar consulta</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item"><a href="/consulta/listarConsultas/">Consultas</a></li>
        <li class="breadcrumb-item"><a href="/consulta/detalhar/{% if treino %}{{ treino.consulta.id}}{%else%}{{ dieta.consulta.id}}{%endif%}/">Consulta</a></li>
        <li class="breadcrumb-item">
            Detalhar {% if treino %}treino {{ treino.get_diaSemana_display }}{%else%}dieta {{ dieta.get_diaSemana_display }}{%endif%}
        </li>
      </ol>
    </nav>
</div><!-- End Page Title -->
{% endblock %}

{% block content %}
<div class="container-fluid py-4">
    

    <div class="row">
        <div class="card">
            <div class="card-header pb-0 p-3">
                <div class="row">
                <div class="col-6 d-flex align-items-center">
                    <h5 class="card-title">Informaçoes sobre {% if treino %}o treino{%else%}a dieta{%endif%}</h5>
                </div>
                </div>
            </div>  
            <div class="card-body p-3">
                {% if treino %}
                    <div class="row mb-3">
                        <div class="col-lg-3 col-md-4 fw-bold">Exercicio</div>
                        <div class="col-lg-9 col-md-8"> {{ treino.exercicio }} </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-lg-3 col-md-4 fw-bold">Dia semana</div>
                        <div class="col-lg-9 col-md-8"> {{ treino.get_diaSemana_display }} </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-lg-3 col-md-4 fw-bold">Repetiçoes</div>
                        <div class="col-lg-9 col-md-8"> {{ treino.repeticao }} </div>
                    </div>
                    
                    <div class="row mb-3">
                        <div class="col-lg-3 col-md-4 fw-bold">Série</div>
                        <div class="col-lg-9 col-md-8"> {{ treino.serie }} </div>
                    </div>
                {% endif %}
                {% if dieta %}
                    <div class="row mb-3">
                        <div class="col-lg-3 col-md-4 fw-bold">Alimento</div>
                        <div class="col-lg-9 col-md-8"> {{ dieta.alimento }} </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-lg-3 col-md-4 fw-bold">Dia semana</div>
                        <div class="col-lg-9 col-md-8"> {{ dieta.get_diaSemana_display }} </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-lg-3 col-md-4 fw-bold">Quantidade</div>
                        <div class="col-lg-9 col-md-8"> {{ dieta.quantidade }} </div>
                    </div>
                    
                    <div class="row mb-3">
                        <div class="col-lg-3 col-md-4 fw-bold">Horario</div>
                        <div class="col-lg-9 col-md-8"> {{ dieta.horario }} </div>
                    </div>
                {% endif %} 
          
        </div>        
    </div>
</div>
{% endblock %}

code/core/templates/editarPlanoTrabalho.html
{% extends 'Base.html' %}
{% load bootstrap %}

{% load static %}

{% block head %}
<title>Agenda de {{ request.user.username }} </title>
{% endblock %}

{% block pagetitle %}
<div class="pagetitle">
    <h1>Gerenciar consulta</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item"><a href="/consulta/listarConsultas/">Consultas</a></li>
        <li class="breadcrumb-item"><a href="/consulta/detalhar/{% if treino %}{{ treino.consulta.id}}{%else%}{{ dieta.consulta.id}}{%endif%}/"> Consulta</a></li>
        <li class="breadcrumb-item">
            Editar {% if treino %}treino {{ treino.get_diaSemana_display }}{%else%}dieta {{ dieta.get_diaSemana_display }}{%endif%}
        </li>
      </ol>
    </nav>
</div><!-- End Page Title -->
{% endblock %}
{% block content %}
<div class="container-fluid py-4">
    

    <div class="row">
        <div class="card">
            <div class="card-header pb-0 p-3">
                <div class="row">
                <div class="col-6 d-flex align-items-center">
                    <h5 class="card-title">Editar {% if treino %}o treino{%else%}a dieta{%endif%}</h5>
                </div>
                </div>
            </div>  
            <div class="card-body p-3">
            
                <form action="." method="post" novalidate>
                    {% csrf_token %}
                    {{ form|bootstrap }}
                    <div class="modal-footer">
                        <input type="submit" class="btn btn-primary" value="Salvar">
                      </div>
                </form>
          
        </div>        
    </div>
</div>
{% endblock %}

code/core/templates/perfilProfissional.html
{% extends 'Base.html' %}
{% load static %}

{% block head %}
<title> {{ profissional.last_name }} no NutriAtivo </title>
{% endblock %}

{% block pagetitle %}

<div class="pagetitle">
    <h1>Perfil profissional</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item"><a href="/consulta/procurar_profissional/">Pesquisar</a></li>
        <li class="breadcrumb-item">Perfil de profissional</li>
      </ol>
    </nav>
</div>

{% endblock %}

{% block content %}
<section class="section profile">
    <div class="row">
      <div class="col-xl-4">

        <div class="card">
          <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">

            <img src="{% if profissional.foto %} {{ profissional.foto.url }} {% else %} {% static 'img/profile-placeholder.jpg' %} {% endif %}" alt="Profile" class="rounded-circle">
            <h2>{{ profissional.first_name }} {{ profissional.last_name }}</h2>
            <h3>{% if profissional.tipo == 'N' %} Nutricionista {% elif profissional.tipo == 'ED' %} Educador Físico {% endif %}</h3>
            <div class="social-links mt-2">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>
          </div>
        </div>

      </div>

      <div class="col-xl-8">

        <div class="card">
          <div class="card-body pt-3">
            <!-- Bordered Tabs -->
            <ul class="nav nav-tabs nav-tabs-bordered">

              <li class="nav-item">
                <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-overview">Overview</button>
              </li>

              <li class="nav-item">
                <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-horarios">Horarios disponiveis</button>
              </li>

            </ul>
            <div class="tab-content pt-2">

              <div class="tab-pane fade  profile-overview" id="profile-overview">
                <!-- <h5 class="card-title">About</h5> -->
                <!-- <p class="small fst-italic">Sunt est soluta temporibus accusantium neque nam maiores cumque temporibus. Tempora libero non est unde veniam est qui dolor. Ut sunt iure rerum quae quisquam autem eveniet perspiciatis odit. Fuga sequi sed ea saepe at unde.</p> -->

                <h5 class="card-title">Detalhes do perfil</h5>

                <div class="row">
                  <div class="col-lg-3 col-md-4 label ">Nome completo</div>
                  <div class="col-lg-9 col-md-8">{{ profissional.first_name }} {{ profissional.last_name }}</div>
                </div>

                <div class="row">
                  <div class="col-lg-3 col-md-4 label">Profissição</div>
                  <div class="col-lg-9 col-md-8">{% if profissional.tipo == 'N' %} Nutricionista {% elif profissional.tipo == 'EF' %} Educador Físico {% endif %}</div>
                </div>

                {% if profissional.localAtendimento  %}
                <div class="row">
                  <div class="col-lg-3 col-md-4 label">Local atendimento</div>
                  <div class="col-lg-9 col-md-8"> {{ profissional.localAtendimento }}</div>
                </div>
                {% endif %}

                <div class="row">
                  <div class="col-lg-3 col-md-4 label">Email</div>
                  <div class="col-lg-9 col-md-8">{{ profissional.email }}</div>
                </div>

              </div>

              <div class="tab-pane show active fade pt-3" id="profile-horarios">

                <!-- Settings Form -->
                <form method="post" action="{% url 'criar_consulta' %}" id="formHorario">
                  {% csrf_token %}
                  <input type="hidden" name="horario" id="input-horario">
                  <div class="container">
                      <div id="calendar"></div>
                      <div class="modal fade" id="eventModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLabel">Sobre o Hórario</h5>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
                            </div>
                            <div class="modal-body">
                                <p id="eventTitle"></p>
                                <p id="eventStart"></p>
                                <p class="local"> Local de atendimento: {% if profissional.localAtendimento  %} {{ profissional.localAtendimento }} {% else %} Não definido {% endif %}</p>
                            </div>
                            <div class="modal-footer">
                                  <button type="submit" class="btn btn-primary">Marcar consulta</button>

                                  <button type="button" class="btn btn-secondary close-btn" data-bs-dismiss="modal">Fechar</button>
                      
                                    <script>
                                        const modal = document.getElementById('eventModal');
                                        const close_btn = document.querySelector(".close-btn");
                      
                                        close_btn.addEventListener("click", () => {
                                                modal.style.display = 'none';
                            
                                                modal.classList.remove('show');
                                                modal.classList.add('hide');
                                            })
                                    </script>
                            </div>
                            
                          </div>
                        </div>
                      </div>
                  </div>
                </form><!-- End settings Form -->

              </div>

            </div><!-- End Bordered Tabs -->

          </div>
        </div>

      </div>
    </div>
  </section>

<!-- Modal inicio -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js'></script>

<script>
  const list = [
    {% for evento in horarios %}
      {
        title: '{{ evento.hora }}',
        start: '{{ evento.data|date:"Y-m-d" }}',
        end: '{{ evento.data|date:"Y-m-d" }}',
        id_horario: '{{ evento.id }}',
        data: '{{ evento.data }}',
        horario: '{{ evento.get_data_display }}'

      },
      {% endfor %}
    ]

  document.addEventListener('DOMContentLoaded', function() {
      const calendarEl = document.getElementById('calendar');
      const inputHorario = document.getElementById('input-horario')
      const calendar = new FullCalendar.Calendar(calendarEl, {
        initialView: 'dayGridMonth',
        events: list,
        eventClick: function(info) {
                  // Obtém os dados do evento
                  const event = info.event;

                  if (event ) {
                    
                    // Preenche as informações do evento no modal
                    document.getElementById('eventStart').textContent = `Data: ${event.extendedProps.data} dás ${event.extendedProps.horario}  `;
                    inputHorario.value = String(event.extendedProps.id_horario);
                    // Abre o modal
                    const modal = document.getElementById('eventModal');

                    modal.style.display = 'block';

                    // Adicione aqui a lógica para preencher o modal com os dados do evento clicado

                    modal.classList.add('show');
                    modal.classList.remove('hide');
                  }
              }
      });
      calendar.render();
      calendarEl.style.minHeight = '400px';
  });
</script>

{% endblock%}

code/core/templates/sidebar.html
{% load static %}

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">
      {% if user.is_authenticated %}
              {% if user.groups.exists %}
                {% for group in user.groups.all %}
                    {% if group.name == 'Administrador' %}
                      <li class="nav-item">
                        <a class="nav-link collapsed" href="{% url 'listar_usuarios_pendentes' %}">
                          <i class="fas fa-box-check"></i>
                          <span>Autorizar usuarios</span>
                        </a>
                      </li>
                    {% elif group.name == 'Cliente'%}
                      <li class="nav-item active">
                        <a class="nav-link collapsed" href="{% url 'procurar_profissional' %}">
                          <i class="fas fa-search"></i>
                          <span>Procurar consulta</span>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link collapsed" href="{% url 'listar_consultas' %}">
                          <i class="fas fa-clipboard-check"></i>
                          <span>Consultas</span>
                        </a>
                      </li>
                    {% elif group.name == 'Nutricionista' or group.name == 'Educador Fisico' %}
                      <li class="nav-item">
                        <a class="nav-link collapsed" href="{% url 'listar_consultas' %}">
                          <i class="fas fa-clipboard-check"></i>
                          <span>Consultas</span>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link collapsed" href="{% url 'gerenciarHorario' %}">
                          <i class="fas fa-calendar"></i>
                          <span>Agenda</span>
                        </a>
                      </li>
                    {% endif %}
                {% endfor %}
              {% endif %}
            {% else %}

            <li class="nav-item">
              <a class="nav-link collapsed" href="{% url 'login' %}">
                <i class="fas fa-dumbbell"></i>
                <span>Login</span>
              </a>
            </li>
            {% endif %}  
    </ul>

  </aside><!-- End Sidebar-->